#
  #  Copyright (c) 2023 ZF Friedrichshafen AG
  #  Copyright (c) 2023 Mercedes-Benz Tech Innovation GmbH
  #  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
  #  Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
  #
  #  See the NOTICE file(s) distributed with this work for additional
  #  information regarding copyright ownership.
  #
  #  This program and the accompanying materials are made available under the
  #  terms of the Apache License, Version 2.0 which is available at
  #  https://www.apache.org/licenses/LICENSE-2.0
  #
  #  Unless required by applicable law or agreed to in writing, software
  #  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  #  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  #  License for the specific language governing permissions and limitations
  #  under the License.
  #
  #  SPDX-License-Identifier: Apache-2.0
  #

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bdrs.fullname" . }}
  labels:
    {{- include "bdrs.server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bdrs.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bdrs.server.selectorLabels" . | nindent 8 }}
        {{- with .Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bdrs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      {{- if or .Values.server.initContainers .Values.customCaCerts }}
      initContainers:
        {{- if .Values.server.initContainers }}
        {{- toYaml .Values.server.initContainers | nindent 8 }}
        {{- end }}
        {{- if .Values.customCaCerts }}
        - name: custom-cacerts
          # either use the specified image, or use the default one
          {{- if .Values.server.image.repository }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "tractusx/bdrs-server-memory:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              cp /opt/java/openjdk/lib/security/cacerts /workdir/
              find /cacerts -type f \( -iname \*.crt -o -iname \*.pem \) -exec echo "{}" \; | while read PEM_FILE_PATH; do
                PEM_FILE=${PEM_FILE_PATH##*/}
                ALIAS=${PEM_FILE%.*}
                echo "adding ${PEM_FILE} with alias ${ALIAS} to cacerts ..."
                keytool -import -noprompt -trustcacerts -alias ${ALIAS} -file ${PEM_FILE_PATH} -keystore /workdir/cacerts -storepass changeit
              done
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          volumeMounts:
            - name: custom-cacertificates
              mountPath: /cacerts
            - name: custom-cacerts
              mountPath: /workdir
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          # either use the specified image, or use the default one
          {{- if .Values.server.image.repository }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "tractusx/bdrs-server-memory:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          {{- end }}

          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
          {{- range $key,$value := .Values.server.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.server.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.server.endpoints.default.path }}/check/liveness
              port: {{ .Values.server.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.server.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.server.endpoints.default.path }}/check/readiness
              port: {{ .Values.server.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          env:
          {{- if .Values.server.debug.enabled }}
            - name: "JAVA_TOOL_OPTIONS"
            {{- if .Values.server.debug.suspendOnStart }}
              value: >-
                {{ printf "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=%v" .Values.server.debug.port }}
            {{- else }}
              value: >-
                {{ printf "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=%v" .Values.server.debug.port }}
            {{- end }}
          {{- end }}


            #######
            # API #
            #######
            - name: "EDC_API_AUTH_KEY"
              valueFrom:
                secretKeyRef:
                  name: "{{ template "bdrs.secretName" . }}"
                  key: "auth-key"
            - name: "WEB_HTTP_PORT"
              value: {{ .Values.server.endpoints.default.port | quote }}
            - name: "WEB_HTTP_PATH"
              value: {{ .Values.server.endpoints.default.path | quote }}
            - name: "WEB_HTTP_MANAGEMENT_PORT"
              value: {{ .Values.server.endpoints.management.port | quote }}
            - name: "WEB_HTTP_MANAGEMENT_PATH"
              value: {{ .Values.server.endpoints.management.path | quote }}
            - name: "WEB_HTTP_DIRECTORY_PORT"
              value: {{ .Values.server.endpoints.directory.port | quote }}
            - name: "WEB_HTTP_DIRECTORY_PATH"
              value: {{ .Values.server.endpoints.directory.path | quote }}

            ################
            ## POSTGRESQL ##
            ################

            # see extension https://github.com/eclipse-edc/Connector/tree/main/extensions/control-plane/store/sql/asset-index-sql
            - name: "EDC_DATASOURCE_DIDENTRY_NAME"
              value: "didentry"
            - name: "EDC_DATASOURCE_DIDENTRY_USER"
              value: {{ .Values.postgresql.auth.username | required ".Values.postgresql.auth.username is required" | quote }}
            - name: "EDC_DATASOURCE_DIDENTRY_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ template "bdrs.postgresqlSecretName" . }}"
                  key: "password"
            - name: "EDC_DATASOURCE_DIDENTRY_URL"
              value: {{ tpl .Values.postgresql.jdbcUrl . | quote }}

            ######################################
            ## Additional environment variables ##
            ######################################
          {{- range $key, $value := .Values.server.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- range $key, $value := .Values.server.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if and (or .Values.server.envSecretNames .Values.server.envConfigMapNames) (or (gt (len .Values.server.envSecretNames) 0) (gt (len .Values.server.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := .Values.server.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := .Values.server.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.customCaCerts }}
            - name: custom-cacerts
              mountPath: /opt/java/openjdk/lib/security/cacerts
              subPath: cacerts
            {{- end }}
            - name: "tmp"
              mountPath: "/tmp"
      volumes:
        - name: "configuration"
          configMap:
            name: {{ include "bdrs.fullname" . }}
            items:
              - key: "logging.properties"
                path: "logging.properties"
        {{- if .Values.customCaCerts }}
        - name: custom-cacertificates
          configMap:
            name: {{ include "bdrs.fullname" . }}-custom-cacerts
            defaultMode: 0400
        - name: custom-cacerts
          emptyDir:
            sizeLimit: 1Mi
        {{- end }}
        - name: "tmp"
          emptyDir: { }
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
